theme = "monokai_pro"

[editor]
mouse = false
true-color = true

[editor.soft-wrap]
enable = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
