[[language]]
name = "hcl"
language-servers = [ "terraform-ls" ]
language-id = "terraform"
formatter = { command = "terraform" , args = ["fmt", "-"] }

[[language]]
name = "tfvars"
language-servers = [ "terraform-ls" ]
language-id = "terraform-vars"

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]
